mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),

    path('<int:question_id>/', views.details, name='detail'),

    path('<int:question_id>/results/', views.results, name = 'results'),

    path('<int:question_id>/vote/', views.vote, name = 'vote'),
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Data de publicação')
    def __str__(self):
        return ("{0} - {1}").format(self.id, self.question_text)
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return ("{0} - {1}").format(self.question, self.choice_text)

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
#from django.template import loader

from .models import Question, Choice
# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def details(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html',{'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html',{'question':question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice."
            })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% include "polls/header.html" %}
<div class="container mt-5 rounded">
    <div class="list-group">
        <form action="{% url  'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            <div class="list-group-item bg-light">
                <h1>{{ question.question_text }}</h1>
            </div>
            {% if error_message %}
                <div class="alert alert-danger" role="alert">{{ error_message }}</div>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <div class="list-group-item">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                        <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                    </div>
                </div>
            {% endfor %}
            <div class="list-group-item">
                <button class="btn btn-primary" type="submit">Votar</button>
                <a class="btn btn-light" href="{% url 'polls:index' %}">Cancelar</a>
            </div>
        </form>
    </div>
</div>

polls/templates/polls/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <title>Polls</title>
    <link rel="icon" type="image/x-icon" href="https://lh3.google.com/u/0/d/1tgRqJ9z5apZQ_U4oi77rGwU8cnSydXVG=w1920-h922-iv1">
</head>
<body>
    <nav class="navbar navbar-expand-md bg-light">
        <div class="container justify-content-center">
            <a class="navbar-brand" href="{% url 'polls:index' %}">Polls</a>
        </div>
    </nav>

polls/templates/polls/index.html
{% include "polls/header.html" %}

{% load static %}

{% if latest_question_list %}
<div class="container mt-5">
    <div class="row">

        {% for question in latest_question_list %}
            <div class="col-sm-6 col-lg-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{question.question_text}}</h5>
                        <small class="text-muted">{{question.pub_date}}</small>
                    </div>
                    <div class="card-body">
                        <a class="card-link btn btn-primary" href="{% url 'polls:detail' question.id %}">Responder</a>
                        <a class="card-link btn btn-light" href="{% url 'polls:results' question.id %}">Ver resultado</a>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
</div>

{% else %}
<div class="container mt-5 justify-content-center">
    <div class="row d-flex justify-content-center">
        <img class="col-12 col-md-6" src="{% static 'polls/sad.svg' %}" alt="It`s so sad">
    </div>
    <p class="text-center">Sorry! No polls are avaliable</p>
</div>
{% endif %}

polls/templates/polls/results.html
{% include "polls/header.html" %}

<div class="container mt-5">
    <div class="list-group">
        <div class="list-group-item bg-light">
            <h1>{{ question.question_text }}</h1>
        </div>

        {% for choice in question.choice_set.all %}
            <div class="list-group-item">
                {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
            </div>
        {% endfor %}

        <div class="list-group-item">
            <a class="btn btn-primary" href="{% url 'polls:detail' question.id %}">Responder</a>
            <a class="btn btn-light" href="{% url 'polls:index' %}">Voltar ao ínicio</a>
        </div>
    </div>
</div>